# Model
network: LightConvNet
networkArgs: 
  num_classes: 2
  num_samples: 1000
  num_channels: 20
  num_bands: 9
  embed_dim: 64
  win_len: 250
  num_heads: 8
  weight_softmax: True
  bias: False

# Data
dataPath: dataset/openBMI/multifreq
outFolder: output/openBMI

# Training
preferedDevice: gpu
nGPU: 0
randomSeed: 0

batchSize: 200
kFold: 10

maxEpochs: 500
numEpochsEarlyStop: 50
maxEpochsAfterEarlyStop: 200
continueAfterEarlyStop: True

lr: 0.001
lrFactor: 0.6
lrPatience: 20
lrMin: 0.0001


