# Model
network: LightConvNet
networkArgs: 
  num_classes: 2
  num_samples: 1000
  num_channels: 20
  num_bands: 9
  embed_dim: 64
  win_len: 250
  num_heads: 8
  weight_softmax: True
  bias: False

# Data
dataPath: dataset/openBMI/two_seconds/multifreq
outFolder: output/openBMI/two_seconds
subId: 51
filterBank: 
  - [4,8]
  - [8,12]
  - [12,16]
  - [16,20] 
  - [20,24] 
  - [24,28]
  - [28,32]
  - [32,36]
  - [36,40]

# Training
preferedDevice: gpu
nGPU: 0
randomSeed: 0

batchSize: 200
kFold: 10

maxEpochs: 500
numEpochsEarlyStop: 50
maxEpochsAfterEarlyStop: 200
continueAfterEarlyStop: True

lr: 0.001
lrFactor: 0.6
lrPatience: 20
lrMin: 0.0001


